FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# O '-- --host' é essencial para o Vite expor a porta corretamente dentro do Docker, permitindo que seja acessível de fora do container.    
#Front caso haja alterações nas tecnologias, ajuste o dockerfile para refletir essas mundanças.
CMD ["npm", "run", "dev", "--", "--host"]