FROM node:20-alpine

WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências do back
RUN npm install

# Copia o restante do código do back-end
COPY . .

RUN npx prisma generate

# Porta padrão que o Express costuma rodar
EXPOSE 3000

# Comando para iniciar o servidor depois de aplicar as migrations
CMD ["npm", "start"]